/*1344958378,169776069*/

if (window.CavalryLogger) { CavalryLogger.start_js(["GyGms"]); }

__d("Cookie",["Env"],function(a,b,c,d,e,f){var g=b('Env'),h={set:function(i,j,k,l,m){if(g.no_cookies&&i!='tpa')return;document.cookie=i+"="+encodeURIComponent(j)+"; "+(k?"expires="+(new Date(Date.now()+k)).toGMTString()+"; ":"")+"path="+(l||'/')+"; domain="+window.location.hostname.replace(/^.*(\.facebook\..*)$/i,'$1')+(m?"; secure":"");},clear:function(i,j){j=j||'/';document.cookie=i+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; "+"path="+j+"; domain="+window.location.hostname.replace(/^.*(\.facebook\..*)$/i,'$1');},get:function(i){var j=document.cookie.match('(?:^|;\\s*)'+i+'=(.*?)(?:;|$)');return (j?decodeURIComponent(j[1]):j);}};e.exports=h;});
__d("legacy:cookie",["Cookie"],function(a,b,c,d){var e=b('Cookie');a.getCookie=e.get;a.setCookie=e.set;a.clearCookie=e.clear;},3);
__d("AsyncSignal",["Env","ErrorUtils","QueryString","URI","XHR","copyProperties"],function(a,b,c,d,e,f){var g=b('Env'),h=b('ErrorUtils'),i=b('QueryString'),j=b('URI'),k=b('XHR'),l=b('copyProperties');function m(n,o){this.data=o||{};if(g.tracking_domain&&n.charAt(0)=='/')n=g.tracking_domain+n;this.uri=n;}m.prototype.setHandler=function(n){this.handler=n;return this;};m.prototype.send=function(){var n=this.handler,o=this.data,p=new Image();if(n)p.onload=p.onerror=function(){h.applyWithGuard(n,null,[p.height==1]);};o.asyncSignal=(Math.random()*10000|0)+1;var q=new j(this.uri).isFacebookURI();l(o,k.getAsyncParams(q?'POST':'GET'));p.src=i.appendToUrl(this.uri,o);return this;};e.exports=m;});
__d("legacy:async-signal",["AsyncSignal"],function(a,b,c,d){a.AsyncSignal=b('AsyncSignal');},3);
function detect_broken_proxy_cache(a,b){var c=getCookie(b);if((c!=a)&&(c!=null)&&(a!='0')){var d={c:'si_detect_broken_proxy_cache',m:b+' '+a+' '+c},e=new URI('/common/scribe_endpoint.php').getQualifiedURI().toString();new AsyncSignal(e,d).send();}}
function link_rel_preload(){var a=/async(?:-post)?|dialog(?:-pipe|-post)?|theater|toggle/;document.documentElement.onmousedown=function(b){b=b||window.event;var c=b.target||b.srcElement,d=Parent.byTag(c,'A');if(!d)return;var e=d.getAttribute('ajaxify'),f=d.href,g=e||f;if(e&&f&&!(/#$/).test(f)){var h=b.which&&b.which!=1,i=b.altKey||b.ctrlKey||b.metaKey||b.shiftKey;if(h||i)return;}var j=d.rel&&d.rel.match(a);j=j&&j[0];switch(j){case 'dialog':case 'dialog-post':Bootloader.loadComponents('dialog');break;case 'dialog-pipe':Bootloader.loadComponents(['ajaxpipe','dialog']);break;case 'async':case 'async-post':Bootloader.loadComponents('async');break;case 'theater':Bootloader.loadComponents('PhotoSnowlift',function(){PhotoSnowlift.preload(g,d);});break;case 'toggle':Bootloader.loadComponents('Toggler');break;}return;};}
__d("DimensionTracking",["event-extensions","AsyncSignal","Cookie","DOMDimensions","Run","isInIframe"],function(a,b,c,d,e,f){b('event-extensions');var g=b('AsyncSignal'),h=b('Cookie'),i=b('DOMDimensions'),j=b('Run'),k=b('isInIframe');function l(){var m=i.getViewportDimensions();h.set('wd',m.width+'x'+m.height);if(Math.random()<.01)new g('/ajax/dimension_context.php',{x:m.width,y:m.height}).send();}if(!k())j.onAfterLoad(function(){setTimeout(l,100);Event.listen(window,'resize',l);Event.listen(window,'focus',l);});});
__d("ScriptPathState",["Arbiter"],function(a,b,c,d,e,f){var g=b('Arbiter'),h,i,j,k,l=100,m={setIsUIPageletRequest:function(n){j=n;},setUserURISampleRate:function(n){k=n;},reset:function(){h=null;i=false;j=false;},_shouldUpdateScriptPath:function(){return (i&&!j);},_shouldSendURI:function(){return (Math.random()<k);},getParams:function(){var n={};if(m._shouldUpdateScriptPath()){if(m._shouldSendURI()&&h!==null)n.user_uri=h.substring(0,l);}else n.no_script_path=1;return n;}};g.subscribe("pre_page_transition",function(n,o){i=true;h=o.to.getUnqualifiedURI().toString();});e.exports=a.ScriptPathState=m;});
__d("throttleAcrossTransitions",["debounce"],function(a,b,c,d,e,f){var g=b('debounce');function h(i,j,k){return g(i,j,k,true,true);}e.exports=h;});
__d("UserActionHistory",["Arbiter","ClickRefUtils","throttleAcrossTransitions"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('ClickRefUtils'),i=b('throttleAcrossTransitions'),j={click:1,submit:1},k=false,l={log:[],len:0},m=i(function(){try{k._ua_log=JSON.stringify(l);}catch(p){k=false;}},1000);function n(){try{if(a.sessionStorage){k=a.sessionStorage;k._ua_log&&(l=JSON.parse(k._ua_log));}}catch(p){k=false;}l.log[l.len%10]={ts:Date.now(),path:'-',index:l.len,type:'init',iref:'-'};l.len++;g.subscribe("UserAction/new",function(q,r){var s=r.ua,t=r.node,event=r.event;if(!event||!(event.type in j))return;var u={path:window._script_path,type:event.type,ts:s._ue_ts,iref:h.get_intern_ref(t)||'-',index:l.len};l.log[l.len++%10]=u;k&&m();});}function o(){return l.log.sort(function(p,q){return (q.ts!=p.ts)?(q.ts-p.ts):(q.index-p.index);});}n();e.exports={getHistory:o};});