/*1344441038,169776319*/

if (window.CavalryLogger) { CavalryLogger.start_js(["NZQuT"]); }

__d("RequiredFormListener",["event-extensions","Input"],function(a,b,c,d,e,f){b('event-extensions');var g=b('Input');Event.listen(document.documentElement,'submit',function(h){var i=h.getTarget().getElementsByTagName('*');for(var j=0;j<i.length;j++)if(i[j].getAttribute('required')&&g.isEmpty(i[j])){i[j].focus();return false;}},Event.Priority.URGENT);});
__d("curry",["bind"],function(a,b,c,d,e,f){var g=b('bind'),h=g(null,g,null);e.exports=h;});
__d("UnverifiedXD",["XD","XDUnverifiedChannel"],function(a,b,c,d,e,f){var g=b('XD').UnverifiedXD,h=c('XDUnverifiedChannel').channel;g.init({channelUrl:h});e.exports=g;});
__d("PluginConnectButtonEvent",["Arbiter","Plugin","UnverifiedXD"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('Plugin'),i=b('UnverifiedXD'),j={listen:function(k){g.subscribe([h.CONNECT,h.DISCONNECT],function(l,event){if(event.identifier!==k)return;if(typeof event.story_fbid!=='undefined')i.send({type:event.story_fbid>0?'edgeCreated':'edgeRemoved'});},g.SUBSCRIBE_NEW);}};e.exports=j;});
__d("PluginResize",["Log","UnverifiedXD","bind","copyProperties","curry"],function(a,b,c,d,e,f){var g=b('Log'),h=b('UnverifiedXD'),i=b('bind'),j=b('copyProperties'),k=b('curry');function l(o){o=o||document.body;return o.offsetWidth+o.offsetLeft;}function m(o){o=o||document.body;return o.offsetHeight+o.offsetTop;}function n(o,p,event){this.calcWidth=o||l;this.calcHeight=p||m;this.width=undefined;this.height=undefined;this.event=event||'resize';}j(n.prototype,{resize:function(){var o=this.calcWidth(),p=this.calcHeight();if(o!==this.width||p!==this.height){g.debug('Resizing Plugin: (%s, %s, %s)',o,p,this.event);this.width=o;this.height=p;h.send({type:this.event,width:o,height:p});}return this;},auto:function(o){setInterval(i(this,this.resize),o||250);return this;}});n.auto=function(o,event,p){return new n(k(l,o),k(m,o),event).resize().auto(p);};n.autoHeight=function(o,p,event,q){return new n(function(){return o;},k(m,p),event).resize().auto(q);};e.exports=n;});
__d("PluginLikeFlyoutDialog",["Arbiter","DOMEvent","DOMEventListener","DOMQuery","PluginLikeFlyout","PluginResize","Style","copyProperties"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('DOMEvent'),i=b('DOMEventListener'),j=b('DOMQuery'),k=b('PluginLikeFlyout'),l=b('PluginResize'),m=b('Style'),n=b('copyProperties');function o(p,q,r,s){this.parent=new k(p,q,r,s);this.like=r;this.form=p;m.set(r,'width',r.offsetWidth+'px');this.resizeAll();g.subscribe(k.SHOW,this.show.bind(this),g.SUBSCRIBE_NEW);g.subscribe(k.HIDE,this.hide.bind(this),g.SUBSCRIBE_NEW);}n(o.prototype,{resizeAll:function(){var p=this.like;new l(function(){return p.offsetWidth;},function(){return p.offsetHeight;}).resize();},hide:function(){this.resizeAll();},show:function(){var p=j.find(this.form,'.pluginLikeFlyoutFull');new l(function(){return p.offsetWidth;},function(){return p.offsetHeight+p.offsetTop;},'resize.iframe').resize();if(this.subscribed)return;this.subscribed=1;i.add(this.like.parentNode,'click',(function(q){q=new h(q);if(q.target===this.like.parentNode){q.kill();this.parent.hide();}}).bind(this));}});e.exports=o;});
__d("PluginSend",["Arbiter","CSS","DOMDimensions","DOMPosition","DOMQuery","PluginOptin","UnverifiedXD","copyProperties"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('CSS'),i=b('DOMDimensions'),j=b('DOMPosition'),k=b('DOMQuery'),l=b('PluginOptin'),m=b('UnverifiedXD'),n=b('copyProperties'),o='platform/socialplugins/dialog',p='platform/socialplugins/send/sent',q='platform/socialplugins/send/cancel',r=false,s=false,t={type:'presentEdgeCommentDialog',controllerID:'',widget_type:'send',nodeURL:'',width:400,height:300,query:{}},u={close:'dismissEdgeCommentDialog',show:'showEdgeCommentDialog',hide:'hideEdgeCommentDialog'},v={element:null,href:'',canpersonalize:false},w,x,y='';function z(){new l("send").addReturnParams({act:"send"}).start();}function aa(da){if(!v.canpersonalize)return z();if(typeof da!=='string')if(!r){da='open';}else if(s){da='hide';}else da='show';switch(da){case 'open':g.inform(o,{controllerID:y,event:da});r=s=true;var ea=i.getElementDimensions(x),fa=j.getElementPosition(x);t.anchorGeometry={x:ea.width,y:ea.height};t.anchorPosition={x:fa.x,y:fa.y};var ga=ba();t.query.anchorTargetX=ga.x;t.query.anchorTargetY=ga.y;m.send(t);break;case 'close':g.inform(o,{controllerID:y,event:da});r=s=false;break;case 'show':s=true;break;default:s=false;break;}h[s?'show':'hide'](w);h[s?'hide':'show'](x);if(da!=='open')m.send({type:u[da]});}function ba(){var da=k.find(x,'.pluginButtonIcon'),ea=j.getElementPosition(da),fa=i.getElementDimensions(da);return {y:ea.y+fa.width/2,x:ea.x+fa.height/2};}var ca={init:function(da){n(v,da);y=t.controllerID=v.element.id;t.nodeURL=v.href;w=k.find(v.element,'.pluginSendActive');x=k.find(v.element,'.pluginSendInactive');v.element.onclick=aa;g.subscribe(q,function(ea,fa){if(fa.controllerID===y)aa('hide');},g.SUBSCRIBE_NEW);g.subscribe(p,function(ea,fa){if(fa.controllerID===y)aa('close');},g.SUBSCRIBE_NEW);if(da.autosubmit)aa('open');}};a.Arbiter=g;e.exports=ca;});
__d("PluginXDReady",["Arbiter","UnverifiedXD"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('UnverifiedXD'),i={handleMessage:function(j){if(!j.method)return;try{g.inform('Connect.Unsafe.'+j.method,JSON.parse(j.params),g.BEHAVIOR_PERSISTENT);}catch(k){}}};a.XdArbiter=i;h.send({xd_action:'plugin_ready',name:window.name});e.exports=null;});